name: Run Horusec with SARIF Output

on:
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.2.0
        with:
          go-version: '1.16.1'
          check-latest: true
      
      - name: Grab and build Horusec
        run: |
          git clone https://github.com/ZupIT/horusec.git
          cd horusec
          git reset --hard 8659ee7bdb5ca0c82a2eff563523947398c46d63
          make build-dev
          
      - name: Run Horusec
        run: |
          ./horusec/horusec start -p="$GITHUB_WORKSPACE" -O="$GITHUB_WORKSPACE/report.sarif" --output-format="sarif"
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: report.sarif
